language: ruby
rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.5
 - 2.2-head
 - ruby-head
 - jruby-19mode # JRuby in 1.9 mode
 - jruby-head
jdk:
 - openjdk6
 - openjdk7
 - oraclejdk7
gemfile: 
 - gemfiles/Gemfile.rspec2   
 - gemfiles/Gemfile.rspec3   
script: rspec
